### ISSUE TITLE
Request for README

### ISSUE THREAD

**Issue by AJamesPhillips** [ldanon/MetaWards#1]
Hi,

I was informed from Nathan in the WhatsApp chat from this project ( https://coronavirustechhandbook.com/ ) that this repo is used for this paper: https://www.medrxiv.org/content/medrxiv/early/2020/02/14/2020.02.12.20022566.full.pdf

It would be great to confirm that and understand more about this project.  Including what the data is that it contains, the model (i.e. relationships between data), assumptions etc.

There's a potential open source modelling simulation here: https://github.com/TheWorldSim/world-sim/issues/10 and it would be great to reuse this repo if it's appropriate too.  To understand more about TheWorldSim please see this short video: https://www.youtube.com/watch?v=nOzVR5eq1D0&list=PLjlisGLENW0vipuHepcwHZlON86vRyzCm

Cheers!
AJP

**Comment by ldanon** [comment]
Thanks, working on it
